### ISSUE TITLE
Question about VLANs

### ISSUE THREAD

**Issue by ymilord** [riptidewave93/Openwrt-MR24#2]
First off, Thank you for getting OpenWrt running on the MR24. Epic, Epic work. 

I have everything running and installed, I am now at the stage to configure VLANs. And it seems like that's not possible? Is it something that can not be done via the GUI and has to be done via the CLI? Or it does not support it? The stock firmware did.

Any guidance or am I missing something?

Thanks

**Comment by riptidewave93** [comment]
I may be 3 years late, but better late than never! You should be able to do VLANs via OpenWRT using either the UI, or CLI. Documentation is at https://openwrt.org/docs/guide-user/network/vlan/switch_configuration
